apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
spec:
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
    spec:
      containers:
        - name: calculator-api
          image: calculator-api:latest
          imagePullPolicy: Never  # If using local docker build
          env:
            - name: FLASK_ENV
              value: "production"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-api
spec:
  selector:
    app: calculator-api
  ports:
    - port: 5000
      targetPort: 5000
  clusterIP: None
