apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    # ---------- FRONTEND ----------
    - host: frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3002

    # ---------- API (Todos + Calculator) ----------
    - host: api.local
      http:
        paths:
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: todo-app
                port:
                  number: 3000

          - path: /calc
            pathType: Prefix
            backend:
              service:
                name: calculator-api
                port:
                  number: 5000

    # ---------- HEALTH ----------
    - host: health.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: health-monitor
                port:
                  number: 3001
